services:
  - type: web
    name: sepo-certification-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/logs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
