name: Android APK CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install SDK packages
        continue-on-error: true
        run: |
          sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          # Accept licenses; suppress stderr to avoid SIGPIPE causing failure.
          yes | sdkmanager --licenses > /dev/null 2>&1 || echo "licenses accepted"
        shell: bash

      - name: Build Debug and Release APKs
        working-directory: android-app
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon clean assembleDebug assembleRelease

      - name: Rename Debug APK to sepo.apk
        run: |
          cp android-app/app/build/outputs/apk/debug/app-debug.apk android-app/app/build/outputs/apk/debug/sepo.apk

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: sepo-apk
          path: android-app/app/build/outputs/apk/debug/sepo.apk

      - name: Upload Release APK (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned-apk
          path: android-app/app/build/outputs/apk/release/app-release-unsigned.apk


